spring:
  application:
    name: codecanvas
  datasource:
    url: jdbc:mysql://localhost:3306/codecanvas
    username: oxxultus
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update 사용, 프로덕션에서는 validate 추천
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  address: 0.0.0.0